### PR TITLE
migrating to swift2

### PR DESCRIPTION
**Pull request by sibelius**
Migrating to Swift2

Updating Podfile Libs

I'm receiving a build failed, maybe this question could help to solve this issue (http://stackoverflow.com/questions/24206732/cant-use-swift-classes-inside-objective-c)

### CODE REVIEW

**Comment by TosinAF** [comment]
Changing the SWIFT_OPTIMIZATION_LEVEL to -Owholemodule seemed to fix the issue

**Comment by TosinAF** [comment]
I've moved to Swift 2 and committed on master so if you can play with that. Credited you in the git commit. Sorry i was unable to fork this.

**Comment by sibelius** [comment]
It's fine, thanks.

Nice code by the way

**Comment by TosinAF** [comment]
Thanks! and thanks for your help! 
Any reason u decided to help out? Like in the idea?

**Comment by sibelius** [comment]
I was looking for an example code of how to use Cartography because I think Storyboard is not great for team development.

Your ideia is cool. CodeAcademy only has videos on their mobile apps yet.

Maybe you should take a look at react native, it should be useful to reduce the development time

**Pull request closed without merging**
